### ISSUE TITLE
How to increase the TLA balance in Sandbox?

### ISSUE THREAD

**Issue by Eduardogbg** [near/near-workspaces-rs#156]
I've read the docs and the source and it seems to me that there's no way to change how much initial balance the Sandbox TLA gets when created. That makes it impossible for me to run my tests, am I missing something?

**Comment by veigajoao** [comment]
You should fetch the root account, which has an enormous balance, more than enough for anything you might want to do in your tests.

```
let worker: Worker<Sandbox> = workspaces::sandbox().await?;

let root = worker.root_account();

root.create_subaccount(worker, account_id)
    .initial_balance(USER_ACCOUNT_BALANCE)
    .transact()
    .await
    .unwrap()
    .unwrap()
```

**Comment by shariffdev** [comment]
@frol  Let's close this issue as it has been solved.

**Comment by frol** [comment]
@shariffdev This should be documented to be completely resolved.
