### ISSUE TITLE
RPCaas support with API keys

### ISSUE THREAD

**Issue by austinabell** [near/near-workspaces-rs#184]
Currently, our APIs for all networks are pointing at base free RPC nodes, where for more heavy-load or to connect with console, it would be beneficial to hit these endpoints.

API is opinionated on how this is done, but ideally this has little duplication because the only thing that changes for each network is the URL and adding API keys.

**Comment by miraclx** [comment]
`near-jsonrpc-client` has `auth::ApiKey` that workspaces can build atop of. — https://github.com/near/near-jsonrpc-client-rs/blob/master/src/auth.rs

**Comment by shariffdev** [comment]
This can be closed @frol
