### ISSUE TITLE
Add convenience functions for working with Account and Contract types

### ISSUE THREAD

**Issue by ChaoticTempest** [near/near-workspaces-rs#28]
Instead of passing contract/account into `worker.call()`, we can add some wrappers around it within account/contract itself.

For instance, `account.create_account` or `contract.view` would be more ergonomic

Non-exhaustive list of helpers:

*   account
*   <span class="error">[x]</span> create_account (sub-account)
*   [ ] create_and_deploy
*   <span class="error">[x]</span> balance / available_balance
*   <span class="error">[x]</span> delete (deletes the account, and sends balance to beneficiary)

*   contract
*   <span class="error">[x]</span> call
*   <span class="error">[x]</span> view
*   <span class="error">[x]</span> view_code
*   [ ] view_state
*   [ ] patch_state (sandbox only)

**Comment by shariffdev** [comment]
@frol I worked on this one and it can be closed.
