### ISSUE TITLE
`view_state` stopped working

### ISSUE THREAD

**Issue by Tarnadas** [near/near-workspaces-rs#281]
Hey,

I have a script to deploy my contract.
As preparation I read all keys to clean up storage for a redeployment and I use workspaces for this.
However just recently the call to `view_state` returns an error:

```
Error: unable to fulfill the query request

Caused by:
    error while parsing method call result: [data did not match any variant of untagged enum QueryResponse]
```

I changed my code to manually call the RPC server via this query and it works:
```json
{
  "jsonrpc": "2.0",
  "id": "dontcare",
  "method": "query",
  "params": {
    "request_type": "view_state",
    "finality": "final",
    "account_id": "app4.orderly-spot.testnet",
    "prefix_base64": ""
  }
}
```
So it seems like the error must be in the workspaces crate.

**Comment by frol** [comment]
@Tarnadas Did you compile your contract / workspaces-rs project with Rust <= 1.69? See this issue for more details: https://github.com/near/nearcore/issues/9143

**Comment by Tarnadas** [comment]
Hey @frol,
yes I'm aware of the issue and use Rust 1.69.
But why should the Rust version that I use for compilation affect this? Isn't workspaces doing an RPC call and not doing anything on chain in my case?

**Comment by Tarnadas** [comment]
Ah ok, that makes it clear. But I don't use workspaces to compile my code. I have a build script and just load the wasm file for deployment.

In this particular case I don't use workspaces for integration tests, but instead I have a deploy program for testnet. I read the existing contract state to delete existing keys and do a deployment afterwards.

**Comment by frol** [comment]
@Tarnadas If you don't use workspaces-rs, submit your issue somewhere it belongs to and provide more details with the code you run, otherwise it is impossible to help you.

**Comment by shariffdev** [comment]
Is this issue still relevant, If it is stale we can close it.

**Comment by frol** [comment]
@Tarnadas Please, try using the latest `near-workspaces` 0.9 release and feel free to reopen this issue if it still fails for you
