### ISSUE TITLE
Add API for measuring gas

### ISSUE THREAD

**Issue by ChaoticTempest** [near/near-workspaces-rs#29]
Currently, we'd comb through the `CallExecution` outcomes from certain functions that emit this value such as `call` (but not all function will emit it) to get the used gas. And then later, we add it all up to get the total gas consumed. We can ease this by having some sort of `GasMeter` that would measure changes between each call, or whenever we want to get the elapsed gas used. 

This would potentially look like this:
 ```rust
 let meter = GasMeter::now(worker);
 ...
 worker.call(...);
 ...
 println!("Gas used: {} yoctoNear", meter.elapsed().as_yocto());

```

**Comment by itsyaasir** [comment]
@frol This issue looks interesting, while I got the general idea of the issue, can someone expound it more? Thanks

In the meantime am still studying up the source code.

**Comment by itsyaasir** [comment]
- One idea I got for solving this is, after we initialize the `GasMeter`, and do bunch of calls, we can comb through the blocks to get the transaction outcomes and add up the gas used. (I feel this is inefficient)
- It will be helpful if someone could guide me through this as am new to the nearprotocol.

Any other suggestions are welcome, Thanks.

**Comment by ChaoticTempest** [comment]
When I was writing the reference syntax, what I had in mind was to have `GasMeter` directly hook onto when worker would make `call`s and add up all the gas it's seen. Worker here shouldn't be storing anything but should offer hooks like `set_on_transact(fn)`. This is a bit more difficult ticket if you're unfamiliar with the codebase as it requires restructuring it to have these hooks, but feel free to play around with the idea

**Comment by frol** [comment]
@ChaoticTempest Do I understand correctly that you want to measure only the gas used specifically for the function call execution and ignore all the other costs? What is the benefit over just using the total gas used?

If I understood this issue correctly, #284 is not going in the right direction, right? I think it would be helpful if you share the problem you think we can solve with this feature.

**Comment by ChaoticTempest** [comment]
@frol this feature is meant to allow monitoring gas usage over multiple calls/transactions, so people don't have to manually add them all up themselves.

Roughly, this is what it should do:
```rust
let meter = GasMeter::now(&worker);
account.call(...)
acocunt.call(...)
...
let total_gas_usage = meter.elapsed();
println!("{}", total_gas_usage);
```

This is purely syntax sugar over:
```rust
let mut total_gas_usage = 0;
let result = account.call(...)
total_gas_usage += result.total_gas_burnt;

let result = account.call(...)
total_gas_usage += result.total_gas_burnt;

println!("{}", total_gas_usage);
```

Where the `GasMeter` is really helpful is to not have to manually tally all these burnt gas counts where the developer can potentially miss adding it themselves in more complex tests that are making more of these calls in various codepaths.

From what I see currently of #284, it doesn't accomplish this. I'll comment more over there about the specifics
