### ISSUE TITLE
Incorrect minimum Rust version (1.69.0)

### ISSUE THREAD

**Issue by mooori** [near/near-workspaces-rs#336]
According to [docs](https://github.com/near/near-workspaces-rs/tree/near-workspaces-v0.9.0#requirements), `near-workspaces@v0.9.0` should support Rust v1.69.0 and up. However, tests using `near-workspaces` with Rust 1.69.0 can not compile. We face that issue with [`near-plugins`](https://github.com/aurora-is-near/near-plugins) and the same issue popped up [here](https://github.com/aurora-is-near/rainbow-token-connector/pull/234/files#r1360339766).

### Background

`near-workspaces` depends on `anstyle v1.0.4`, which [requires at least Rust 1.70.0](https://github.com/rust-cli/anstyle/blob/04b194bd03642992b4d1f70628d04f1f22fc381a/Cargo.toml#L8).

```
cargo tree -i anstyle
anstyle v1.0.4
├── anstream v0.6.4
│   └── clap_builder v4.4.7
│       └── clap v4.4.7
│           └── near-o11y v0.17.0
│               └── near-chain-configs v0.17.0
│                   ├── near-jsonrpc-client v0.6.0
│                   │   └── near-workspaces v0.9.0
│                   │       [dev-dependencies]
│                   │       └── near-plugins-derive v0.v0.1.0 (proc-macro)
│                   │           └── near-plugins v0.1.0
```

### Why didn’t this break `near-workspaces` CI?

Perhaps there is no action checking that the stated minimum Rust version is actually supported? At least [this test run](https://github.com/near/near-workspaces-rs/actions/runs/6744509615/job/18334497288#step:3:18) appears to be using the latest Rust version (1.73.0).

### One way to reproduce this

- Checkout [this commit](https://github.com/aurora-is-near/near-plugins/commit/d3c54045bd59fcbe34508664c14f3c63b240068b) of the `rust-version` branch of `near-plugin`’s.
- Apply below diff to use Rust 1.69.0 and then run `cargo test --workspace`

```diff
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -12,7 +12,7 @@ version = "0.15.0"
 version = "0.1.0"
 edition = "2021"
 authors = ["Aurora Labs <hello@aurora.dev>"]
-rust-version = "1.70.0"
+rust-version = "1.69.0"
 description = "Ergonomic plugin system to extend NEAR contracts."
 license = "CC0-1.0"
 readme = "README.md"
diff --git a/rust-toolchain b/rust-toolchain
index 1cba0df..6649306 100644
--- a/rust-toolchain
+++ b/rust-toolchain
@@ -1,4 +1,4 @@
 [toolchain]
-channel = "1.70.0"
+channel = "1.69.0"
 components = ["clippy", "rustfmt"]
 targets = [ "wasm32-unknown-unknown" ]
```

**Comment by frol** [comment]
@mooori We cannot stop leaf dependencies from upgrading and breaking MSRV, and there is no requirement to bump MSRV for near-workspaces-rs when you can still use older leaf dependency that supports MSRV:

See how near-sdk-rs pins the dependencies to check that near-sdk-rs itself is still 1.69.0 compatible: 
https://github.com/near/near-sdk-rs/blob/ee5cf867741d6d0d4db15857609b9e9268cc9b32/.github/workflows/test.yml#L26-L32

```
cargo update -p anstyle --precise 1.0.2
cargo update -p anstyle-parse --precise 0.2.1
```

I wish cargo could be smarter about MSRV requirements and pull compatible versions of the dependencies.

**Comment by mooori** [comment]
Since `near-workspaces@0.9` depends on two versions of `clap`, unfortunately this becomes a bit more tricky. So, for instance, downgrading `clap` requires `-p clap@4.4.7` instead of just `-p clap`. I assume this requires updating the command once a new version of `clap` is released, as described in [this comment](https://github.com/aurora-is-near/near-plugins/blob/2e601c59e79bd48d18c1192969a9fee3de6e199e/scripts/fix_dependencies.sh#L9-L13).

**Comment by frol** [comment]
@mooori I hope to cut new versions of near-* crates from nearcore until the end of this month, and then near-o11y will be removed from the dependency tree and this issue will be gone.
