### ISSUE TITLE
`dev_deploy` not working after nearcore 1.37 is released

### ISSUE THREAD

**Issue by gagdiez** [near/near-workspaces-rs#354]
`sandbox.dev_deploy(...)` creates top-level-accounts in the form `dev-X-Y`. Creating TLA of any kind is no longer possible in NEAR (before nearcore v1.37, users could create TLA with >32 chars), for which `dev_deploy` is now broken.

**Comment by frol** [comment]
I removed 0.7.1 release for near-sandbox from crates.io and will release it as 0.8.0 release later this week.

near-workspaces-rs and near-workspaces-js have to be adjusted to work with the new protocol rules for TLA accounts.w

**Comment by volovyks** [comment]
@gagdiez I assume [this](https://github.com/near/near-workspaces-rs/issues/353) issue exists for the same reason.

**Comment by AlexKushnir1** [comment]
I will fix it
